export const botsInintialState = {
    loading: false,
    bots: {
        data: {
            335: {
                id: 335,
                name: 'For fronted tests',
                description: 'don\'t delete it please',
                start_datetime: null,
                aa_base_file_path: 'name path',
                aa_bot_name: 'dfdfd',
                created_at: '2019-11-20T10:29:55+02:00',
                status: {
                    code: 'idle',
                    title: 'All',
                },
                vdi: {
                    id: 2,
                    app_name: 'aaaad',
                    app_common_name: 'aaa',
                    user_name: 'DIRECTORY\\botrunner.one',
                    app_credentials_password: 'Neural#123',
                    vdi: 'EC2AMAZ-67MQ14J.directory.nu.com',
                    vdi_common_name: 'aaa 2',
                },
                variables: [],
                files: [
                    {
                        id: 352,
                        bot_id: 335,
                        name: 'annotation-highlight.pdf',
                    },
                    {
                        id: 354,
                        bot_id: 335,
                        name: 'annotation-highlight (1).pdf',
                    },
                ],
                users: [
                    {
                        id: 6,
                        status: 'disabled',
                        first_name: 'Alyona',
                        last_name: 'Shadrina',
                        avatar: 'storage/avatars/tULQWWAqxpFKRfzBMFCIOMoj3ZIN3H3gnPC05Tpq.png',
                        email: 'alyon.shadrina@gmail.com',
                        role: 'admin',
                        manager: null,
                        manager_users_count: 0,
                        created_at: '2019-10-25T12:18:52+03:00',
                    },
                ],
            },
            3182: {
                id: 3182,
                name: 'qa',
                description: '',
                start_datetime: '2019-11-29T12:37:58+02:00',
                aa_base_file_path: 'My Tasks\\Sample Tasks\\',
                aa_bot_name: 'Prompt.atmx',
                created_at: '2019-11-27T10:04:57+02:00',
                status: {
                    code: 'idle',
                    title: 'All',
                },
                users: [
                    {
                        id: 1,
                        status: 'disabled',
                        first_name: 'Admin',
                        last_name: 'Test',
                        avatar: 'storage/avatars/L7APzDaZm8yBauTHDIj8GRjUZnSMfVgirfPRhQFM.png',
                        email: 'admin@test.com',
                        role: 'admin',
                        manager: null,
                        manager_users_count: 0,
                        created_at: '2019-10-17T11:06:34+03:00',
                    },
                ],
            },
            3183: {
                id: 3183,
                name: 'frontend_devs_bot',
                description: 'don\'t delete it pease',
                start_datetime: '2019-11-29T09:57:03+02:00',
                aa_base_file_path: 'My Tasks\\Sample Tasks\\',
                aa_bot_name: 'apitestapi.atmx',
                created_at: '2019-11-27T12:08:36+02:00',
                status: {
                    code: 'idle',
                    title: 'All',
                },
                users: [
                    {
                        id: 6,
                        status: 'disabled',
                        first_name: 'Alyona',
                        last_name: 'Shadrina',
                        avatar: 'storage/avatars/tULQWWAqxpFKRfzBMFCIOMoj3ZIN3H3gnPC05Tpq.png',
                        email: 'alyon.shadrina@gmail.com',
                        role: 'admin',
                        manager: null,
                        manager_users_count: 0,
                        created_at: '2019-10-25T12:18:52+03:00',
                    },
                    {
                        id: 1,
                        status: 'disabled',
                        first_name: 'Admin',
                        last_name: 'Test',
                        avatar: 'storage/avatars/L7APzDaZm8yBauTHDIj8GRjUZnSMfVgirfPRhQFM.png',
                        email: 'admin@test.com',
                        role: 'admin',
                        manager: null,
                        manager_users_count: 0,
                        created_at: '2019-10-17T11:06:34+03:00',
                    },
                    {
                        id: 3,
                        status: 'disabled',
                        first_name: 'Test',
                        last_name: 'Manager',
                        avatar: null,
                        email: 'test.manager@test.com',
                        role: 'manager',
                        manager: null,
                        manager_users_count: 1,
                        created_at: '2019-10-17T11:06:34+03:00',
                    },
                    {
                        id: 4,
                        status: 'activated',
                        first_name: 'Fmanager',
                        last_name: 'Lmanager',
                        avatar: null,
                        email: 'manager@gmail.com',
                        role: 'manager',
                        manager: null,
                        manager_users_count: 1,
                        created_at: '2019-10-17T14:33:08+03:00',
                    },
                    {
                        id: 5,
                        status: 'activated',
                        first_name: 'Fuser',
                        last_name: 'Luser',
                        avatar: null,
                        email: 'user@gmail.com',
                        role: 'user',
                        manager: {
                            id: 4,
                            status: 'activated',
                            first_name: 'Fmanager',
                            last_name: 'Lmanager',
                            avatar: null,
                            email: 'manager@gmail.com',
                            role: 'manager',
                            manager: null,
                            manager_users_count: 1,
                            created_at: '2019-10-17T14:33:08+03:00',
                        },
                        manager_users_count: 0,
                        created_at: '2019-10-17T14:33:51+03:00',
                    },
                ],
            },
        },
        meta: {},
    },
    userStatuses: {},
    idle: [],
    completed: [],
    in_progress: [],
    scheduled: [],
    failed: [],
    pending: [],
    vdi: [],
    usersForBotCreation: {},
    usersForBotUpdate: {},
};

export const usersInintialState = {
    allUserList: {
        3: {
            id: 3,
            status: 'disabled',
            first_name: 'Test',
            last_name: 'Manager',
            avatar: null,
            email: 'test.manager@test.com',
            role: 'manager',
            manager: null,
            manager_users_count: 1,
            created_at: '2019-10-17T11:06:34+03:00',
        },
        4: {
            id: 4,
            status: 'activated',
            first_name: 'Fmanager',
            last_name: 'Lmanager',
            avatar: null,
            email: 'manager@gmail.com',
            role: 'manager',
            manager: null,
            manager_users_count: 1,
            created_at: '2019-10-17T14:33:08+03:00',
        },
        5: {
            id: 5,
            status: 'activated',
            first_name: 'Fuser',
            last_name: 'Luser',
            avatar: null,
            email: 'user@gmail.com',
            role: 'user',
            manager: {
                id: 4,
                status: 'activated',
                first_name: 'Fmanager',
                last_name: 'Lmanager',
                avatar: null,
                email: 'manager@gmail.com',
                role: 'manager',
                manager: null,
                manager_users_count: 1,
                created_at: '2019-10-17T14:33:08+03:00',
            },
            manager_users_count: 0,
            created_at: '2019-10-17T14:33:51+03:00',
        },
        13: {
            id: 13,
            status: 'disabled',
            first_name: 'User',
            last_name: 'Shad',
            avatar: null,
            email: 'usershad@test.com',
            role: 'user',
            manager: {
                id: 3,
                status: 'disabled',
                first_name: 'Test',
                last_name: 'Manager',
                avatar: null,
                email: 'test.manager@test.com',
                role: 'manager',
                manager: null,
                manager_users_count: 1,
                created_at: '2019-10-17T11:06:34+03:00',
            },
            manager_users_count: 0,
            created_at: '2019-11-18T11:22:45+02:00',
        },
    },
    user: {
        idList: [5, 13],
        meta: {
            pagination: {
                total: 2,
                count: 2,
                per_page: 20,
                current_page: 1,
                total_pages: 1,
                links: {},
            },
        },
    },
    manager: {
        idList: [3, 4],
        meta: {
            pagination: {
                total: 2,
                count: 2,
                per_page: 15,
                current_page: 1,
                total_pages: 1,
                links: {},
            },
        },
    },
};

export const profileInintialState = {
    id: 6,
    first_name: 'Alyona',
    last_name: 'Shadrina',
    avatar: 'storage/avatars/tULQWWAqxpFKRfzBMFCIOMoj3ZIN3H3gnPC05Tpq.png',
    email: 'alyon.shadrina@gmail.com',
    error: null,
    role: 'admin',
    timezone: '+02:00',
};
