import { REDUX_IDENTIFIER } from '../../../config';


export const GET_PROFILE_REQUEST = `${REDUX_IDENTIFIER}GET_PROFILE_REQUEST`;
export const GET_PROFILE_SUCCESS = `${REDUX_IDENTIFIER}GET_PROFILE_SUCCESS`;

export const CHANGE_PROFILE_REQUEST = `${REDUX_IDENTIFIER}CHANGE_PROFILE_REQUEST`;
