import { REDUX_IDENTIFIER } from '../../../config';


export const GET_USERS_FOR_BOT_CREATION_REQUEST = `${REDUX_IDENTIFIER}GET_USERS_FOR_BOT_CREATION_REQUEST`;
export const GET_USERS_FOR_BOT_CREATION_SUCCESS = `${REDUX_IDENTIFIER}GET_USERS_FOR_BOT_CREATION_SUCCESS`;

export const GET_USERS_FOR_BOT_UPDATE_REQUEST = `${REDUX_IDENTIFIER}GET_USERS_FOR_BOT_UPDATE_REQUEST`;
export const GET_USERS_FOR_BOT_UPDATE_SUCCESS = `${REDUX_IDENTIFIER}GET_USERS_FOR_BOT_UPDATE_SUCCESS`;

export const REQUEST_GET_ADMIN_BOT_LIST = `${REDUX_IDENTIFIER}REQUEST_GET_ADMIN_BOT_LIST`;
export const SET_ADMIN_BOT_LIST = `${REDUX_IDENTIFIER}SET_ADMIN_BOT_LIST`;

export const REQUEST_GET_USER_BOT_STATUSES = `${REDUX_IDENTIFIER}REQUEST_GET_USER_BOT_STATUSES`;
export const SET_USER_BOT_STATUSES = `${REDUX_IDENTIFIER}SET_USER_BOT_STATUSES`;

export const REQUEST_GET_BOTS_WITH_STATUS = `${REDUX_IDENTIFIER}REQUEST_GET_BOTS_WITH_STATUS`;
export const SET_BOTS_WITH_STATUS = `${REDUX_IDENTIFIER}SET_BOTS_WITH_STATUS`;

export const REQUEST_GET_BOT = `${REDUX_IDENTIFIER}REQUEST_GET_BOT`;
export const SET_CURRENT_BOT = `${REDUX_IDENTIFIER}SET_CURRENT_BOT`;

export const REQUEST_UPDATE_BOT = `${REDUX_IDENTIFIER}REQUEST_UPDATE_BOT`;
export const REQUEST_UPDATE_BOT_TIME = `${REDUX_IDENTIFIER}REQUEST_UPDATE_BOT_TIME`;

export const REQUEST_CREATE_BOT = `${REDUX_IDENTIFIER}REQUEST_CREATE_BOT`;
export const REQUEST_DELETE_BOT = `${REDUX_IDENTIFIER}REQUEST_DELETE_BOT`;

export const REQUEST_RUN_BOT = `${REDUX_IDENTIFIER}REQUEST_RUN_BOT`;
export const REQUEST_STOP_BOT = `${REDUX_IDENTIFIER}REQUEST_STOP_BOT`;

export const REQUEST_GET_FILES = `${REDUX_IDENTIFIER}REQUEST_GET_FILES`;
export const REQUEST_UPLOAD_FILE = `${REDUX_IDENTIFIER}REQUEST_UPLOAD_FILE`;
export const REQUEST_DELETE_FILE = `${REDUX_IDENTIFIER}REQUEST_DELETE_FILE`;
export const SET_UPLOADED_FILES = `${REDUX_IDENTIFIER}SET_UPLOADED_FILES`;
export const REMOVE_FROM_UPLOADED_FILES = `${REDUX_IDENTIFIER}REMOVE_FROM_UPLOADED_FILES`;

export const REQUEST_GET_VARIABLES = `${REDUX_IDENTIFIER}REQUEST_GET_VARIABLES`;
export const SET_VARIABLES = `${REDUX_IDENTIFIER}SET_VARIABLES`;
export const REQUEST_CREATE_VARIABLE = `${REDUX_IDENTIFIER}REQUEST_CREATE_VARIABLE`;
export const REQUEST_UPDATE_VARIABLE = `${REDUX_IDENTIFIER}REQUEST_UPDATE_VARIABLE`;
export const REQUEST_DELETE_VARIABLE = `${REDUX_IDENTIFIER}REQUEST_DELETE_VARIABLE`;
export const REQUEST_UPDATE_BOT_USERS = `${REDUX_IDENTIFIER}REQUEST_UPDATE_BOT_USERS`;

export const REQUEST_GET_BOT_STATISTICS = `${REDUX_IDENTIFIER}REQUEST_GET_BOT_STATISTICS`;
export const SET_BOT_STATISTICS = `${REDUX_IDENTIFIER}SET_BOT_STATISTICS`;

// VDI
export const GET_ALL_VDI_REQUEST = `${REDUX_IDENTIFIER}GET_ALL_VDI_REQUEST`;
export const GET_ALL_VDI_SUCCESS = `${REDUX_IDENTIFIER}GET_ALL_VDI_SUCCESS`;

export const UPDATE_VDI_REQUEST = `${REDUX_IDENTIFIER}UPDATE_VDI_REQUEST`;
export const UPDATE_VDI_SUCCESS = `${REDUX_IDENTIFIER}UPDATE_VDI_SUCCESS`;

export const CREATE_VDI_REQUEST = `${REDUX_IDENTIFIER}CREATE_VDI_REQUEST`;

export const DELETE_VDI_REQUEST = `${REDUX_IDENTIFIER}DELETE_VDI_REQUEST`;

export const UPDATE_BOT_VDI_REQUEST = `${REDUX_IDENTIFIER}UPDATE_BOT_VDI_REQUEST`;
