import { REDUX_IDENTIFIER } from '../../../config';

// login
export const REQUEST_LOGIN = `${REDUX_IDENTIFIER}REQUEST_LOGIN`;
export const REQUEST_LOGOUT = `${REDUX_IDENTIFIER}REQUEST_LOGOUT`;

export const SET_AUTH_TOKEN = `${REDUX_IDENTIFIER}SET_AUTH_TOKEN`;
export const SET_AUTH_ERROR = `${REDUX_IDENTIFIER}SET_AUTH_ERROR`;
export const REMOVE_AUTH_TOKEN = `${REDUX_IDENTIFIER}REMOVE_AUTH_TOKEN`;

// forgot password
export const REQUEST_FORGOT_PASSWORD = `${REDUX_IDENTIFIER}REQUEST_FORGOT_PASSWORD`;

export const SET_FORGOT_PASSWORD_SENT = `${REDUX_IDENTIFIER}SET_FORGOT_PASSWORD_SENT`;
export const SET_FORGOT_PASSWORD_ERROR = `${REDUX_IDENTIFIER}SET_FORGOT_PASSWORD_ERROR`;

// reset password
export const REQUEST_RESET_PASSWORD = `${REDUX_IDENTIFIER}REQUEST_RESET_PASSWORD`;

// contact
export const REQUEST_CONTACT = `${REDUX_IDENTIFIER}REQUEST_CONTACT`;

export const SET_CONTACT_SENT = `${REDUX_IDENTIFIER}SET_CONTACT_SENT`;
export const SET_CONTACT_ERROR = `${REDUX_IDENTIFIER}SET_CONTACT_ERROR`;
