import { REDUX_IDENTIFIER } from '../../../config';


export const ENQUEUE_SNACKBAR = `${REDUX_IDENTIFIER}ENQUEUE_SNACKBAR`;
export const REMOVE_SNACKBAR = `${REDUX_IDENTIFIER}REMOVE_SNACKBAR`;
export const CLOSE_SNACKBAR = `${REDUX_IDENTIFIER}CLOSE_SNACKBAR`;
