import { REDUX_IDENTIFIER } from '../../../config';

export const GET_USERS_REQUEST = `${REDUX_IDENTIFIER}GET_USERS_REQUEST`;
export const GET_USERS_SUCCESS = `${REDUX_IDENTIFIER}GET_USERS_SUCCESS`;

export const GET_USERS_FOR_MANAGER_REQUEST = `${REDUX_IDENTIFIER}GET_USERS_FOR_MANAGER_REQUEST`;
export const GET_USERS_FOR_MANAGER_SUCCESS = `${REDUX_IDENTIFIER}GET_USERS_FOR_MANAGER_SUCCESS`;

export const GET_MANAGERS_FOR_USER_CREATION_REQUEST = `${REDUX_IDENTIFIER}GET_MANAGERS_FOR_USER_CREATION_REQUEST`;
export const GET_MANAGERS_FOR_USER_CREATION_SUCCESS = `${REDUX_IDENTIFIER}GET_MANAGERS_FOR_USER_CREATION_SUCCESS`;

export const ADD_USER_REQUEST = `${REDUX_IDENTIFIER}ADD_USER_REQUEST`;
export const DELETE_USER_REQUEST = `${REDUX_IDENTIFIER}DELETE_USER_REQUEST`;

export const UPDATE_USER_REQUEST = `${REDUX_IDENTIFIER}UPDATE_USER_REQUEST`;
export const UPDATE_USER_SUCCESS = `${REDUX_IDENTIFIER}UPDATE_USER_SUCCESS`;

export const GET_USER_REQUEST = `${REDUX_IDENTIFIER}GET_USER_REQUEST`;
